### ISSUE TITLE
Checkout Not Working On magento commerce 2.1.9

### ISSUE THREAD

**Issue by magewizard097** [amzn/amazon-payments-magento-2-plugin#137]
Hello,

I am unable to do checkout if I enabled the Amazon pay extension in magento. Its throwing the following js issue on the console. Please advise how to resolve this issue.

amazon-button.js:107 Uncaught ReferenceError: OffAmazonPayments is not defined
    at $.(anonymous function).(anonymous function)._renderAmazonButton (pub/static/frontend/Earthbrand/earththeme/en_US/Amazon_Payment/js/amazon-button.js:107:13)
    at $.(anonymous function).(anonymous function)._renderAmazonButton (pub/static/frontend/Earthbrand/earththeme/en_US/jquery/jquery-ui.js:402:25)
    at $.(anonymous function).(anonymous function)._create (pub/static/frontend/Earthbrand/earththeme/en_US/Amazon_Payment/js/amazon-button.js:44:19)
    at $.(anonymous function).(anonymous function)._create (pub/static/frontend/Earthbrand/earththeme/en_US/jquery/jquery-ui.js:402:25)
    at $.(anonymous function).(anonymous function)._createWidget (pub/static/frontend/Earthbrand/earththeme/en_US/jquery/jquery-ui.js:561:8)
    at new $.(anonymous function).(anonymous function) (pub/static/frontend/Earthbrand/earththeme/en_US/jquery/jquery-ui.js:363:9)
    at $.(anonymous function).(anonymous function) (pub/static/frontend/Earthbrand/earththeme/en_US/jquery/jquery-ui.js:357:11)
    at pub/static/frontend/Earthbrand/earththeme/en_US/mage/apply/main.js:30:17
    at Object.execCb (pub/static/frontend/Earthbrand/earththeme/en_US/requirejs/require.js:1650:33)
    at Object.context.execCb (pub/static/frontend/Earthbrand/earththeme/en_US/mage/requirejs/resolver.js:131:31)
    at Module.check (pub/static/frontend/Earthbrand/earththeme/en_US/requirejs/require.js:866:51)
    at Module.<anonymous> (pub/static/frontend/Earthbrand/earththeme/en_US/requirejs/require.js:1113:34)
    at pub/static/frontend/Earthbrand/earththeme/en_US/requirejs/require.js:132:23
    at pub/static/frontend/Earthbrand/earththeme/en_US/requirejs/require.js:1156:21
    at each (pub/static/frontend/Earthbrand/earththeme/en_US/requirejs/require.js:57:31)
    at Module.emit (pub/static/frontend/Earthbrand/earththeme/en_US/requirejs/require.js:1155:17)
    at Module.check (pub/static/frontend/Earthbrand/earththeme/en_US/requirejs/require.js:917:30)

**Comment by danielneu** [comment]
Hi,

are you sure you followed all steps, including deployment of the statics?

I'm not able to reporoduce and just put an order through on:

Magento Version : 2.1.9
Plugin Version : 1.1.5

Best wishes 
Daniel

**Comment by magewizard097** [comment]
Hi Daniel,

thanks for the reply.
Yes I have followed all the steps including deployments of statics.
But its not working. 

thanks

**Comment by EmilyPepperman** [comment]
We (divegearexpress.com) are live on Magento 2.1.9 and Amazon Pay 1.1.5 and all is working well. :-)

**Comment by magewizard097** [comment]
Just to clarify,We are using magento commerce 2.1.9 not the community version .

**Comment by danielneu** [comment]
Thanks,

will hand this over for investigation.
Please try to follow the template next time, this speeds up the assessment part and reduces the time to resolve.

Best wishes 
Daniel

**Comment by danielneu** [comment]
Hi,

we still have not been able to reproduce this issue on Magento Commerce Edition 2.1.9.
We are still testing with different browsers and systems, but o far this issue was not reproducible.

Anything you can add which helps us troubleshoot would be appreciated.

Best wishes 
Daniel

**Comment by magewizard097** [comment]
Hi Daniel,.

The extension is has one conflict with magestore social login. After we fix
that it started working.

Thanks

**Comment by danielneu** [comment]
Thanks for the information. @magewizard097 

Are you willing to share how you solved the conflict?
This can also be done via email, if you don't want to make this public here: payments-cp-devel@amazon.com

Best wishes 
Daniel

**Comment by craigcarnell** [comment]
@danielneu Same Issue on Magento EE 2.2.1

```
Uncaught ReferenceError: OffAmazonPayments is not defined
    at $.(anonymous function).(anonymous function)._renderAmazonButton (http://www.vax2.co.uk.local/static/version1510662265/frontend/VaxLtd/uk/en_GB/Amazon_Payment/js/amazon-button.js:107:13)
    at $.(anonymous function).(anonymous function)._renderAmazonButton (http://www.vax2.co.uk.local/static/version1510662265/frontend/VaxLtd/uk/en_GB/jquery/jquery-ui.js:402:25)
    at $.(anonymous function).(anonymous function)._create (http://www.vax2.co.uk.local/static/version1510662265/frontend/VaxLtd/uk/en_GB/Amazon_Payment/js/amazon-button.js:44:19)
    at $.(anonymous function).(anonymous function)._create (http://www.vax2.co.uk.local/static/version1510662265/frontend/VaxLtd/uk/en_GB/jquery/jquery-ui.js:402:25)
    at $.(anonymous function).(anonymous function)._createWidget (http://www.vax2.co.uk.local/static/version1510662265/frontend/VaxLtd/uk/en_GB/jquery/jquery-ui.js:561:8)
    at new $.(anonymous function).(anonymous function) (http://www.vax2.co.uk.local/static/version1510662265/frontend/VaxLtd/uk/en_GB/jquery/jquery-ui.js:363:9)
    at $.(anonymous function).(anonymous function) (http://www.vax2.co.uk.local/static/version1510662265/frontend/VaxLtd/uk/en_GB/jquery/jquery-ui.js:357:11)
    at http://www.vax2.co.uk.local/static/version1510662265/frontend/VaxLtd/uk/en_GB/mage/apply/main.js:31:17
    at Object.execCb (http://www.vax2.co.uk.local/static/version1510662265/frontend/VaxLtd/uk/en_GB/requirejs/require.js:1650:33)
    at Object.context.execCb (http://www.vax2.co.uk.local/static/version1510662265/frontend/VaxLtd/uk/en_GB/mage/requirejs/resolver.js:131:31)
    at Module.check (http://www.vax2.co.uk.local/static/version1510662265/frontend/VaxLtd/uk/en_GB/requirejs/require.js:866:51)
    at Module.<anonymous> (http://www.vax2.co.uk.local/static/version1510662265/frontend/VaxLtd/uk/en_GB/requirejs/require.js:1113:34)
    at http://www.vax2.co.uk.local/static/version1510662265/frontend/VaxLtd/uk/en_GB/requirejs/require.js:132:23
    at http://www.vax2.co.uk.local/static/version1510662265/frontend/VaxLtd/uk/en_GB/requirejs/require.js:1156:21
    at each (http://www.vax2.co.uk.local/static/version1510662265/frontend/VaxLtd/uk/en_GB/requirejs/require.js:57:31)
    at Module.emit (http://www.vax2.co.uk.local/static/version1510662265/frontend/VaxLtd/uk/en_GB/requirejs/require.js:1155:17)
_renderAmazonButton @ amazon-button.js:107
(anonymous) @ jquery-ui.js:402
_create @ amazon-button.js:44
(anonymous) @ jquery-ui.js:402
_createWidget @ jquery-ui.js:561
$.(anonymous function).(anonymous function) @ jquery-ui.js:363
$.(anonymous function).(anonymous function) @ jquery-ui.js:357
(anonymous) @ main.js:31
execCb @ require.js:1650
context.execCb @ resolver.js:131
check @ require.js:866
(anonymous) @ require.js:1113
(anonymous) @ require.js:132
(anonymous) @ require.js:1156
each @ require.js:57
emit @ require.js:1155
check @ require.js:917
(anonymous) @ require.js:1113
(anonymous) @ require.js:132
(anonymous) @ require.js:1156
each @ require.js:57
emit @ require.js:1155
check @ require.js:917
(anonymous) @ require.js:1113
(anonymous) @ require.js:132
(anonymous) @ require.js:1156
each @ require.js:57
emit @ require.js:1155
check @ require.js:917
enable @ require.js:1143
init @ require.js:774
callGetModule @ require.js:1170
completeLoad @ require.js:1544
onScriptLoad @ require.js:1671
```

**Comment by danielneu** [comment]
Hi @craigcarnell 

forwarded this to our experts.

Best wishes 
Daniel

**Comment by danielneu** [comment]
Hi @craigcarnell 

are you able to share the following?

"Please kindly provide access to the client's development environment where the issue is replicable, this would include admin panel login details and SSH access."

You can share the details via email: payments-cp-devel@amazon.com

Thanks
Daniel

**Comment by danielneu** [comment]
Hi @craigcarnell 

we are not making use of any special Commerce functionality.
The last time we had this issue (this ticket), it was related to another extension.

We are still happy to support, but we would need access to a staging system to investigate.
If you want us to support, please raise a new issue here on github, it is easier to track than closed ones.

Also, please send access details like asked above to the email address given above as well.

Best wishes 
Daniel
